version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    image: lang0602/bruteforce # 우리가 Dockerfile에서 지정했던 app 이름
    ports:
    - 80:80
    links:
    - mongodb
